# Generated by Django 2.2.6 on 2019-10-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191026_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
