# Generated by Django 2.2.6 on 2019-10-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_neighborhood_occupants_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood_buisnesses',
            name='buisness_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
